### ISSUE TITLE
Use example?

### ISSUE THREAD

**Issue by coccoinomane** [Cerlancism/apps-script-router#1]
Hello!

I was looking for a router for my GS Web App when I found your repo, thank you for making it available!

However I am a bit confused on how to include the router in my GS project... could you please provide an example on how to do that?

Thank you very much,
Guido

**Comment by Cerlancism** [comment]
Thank you for your interest.

Run `npm run build` and copy the compiled script into AppsScript or with [clasp](https://github.com/google/clasp)

This is very basic. You create an object literal and it's properties and nested objects will be the paths.

Example in vanilla js:
```js

function doGet(request)
{
    return new AppsScriptRouter.Handler(root).handleGet(request)
}

function doPost(request) 
{
    return new AppsScriptRouter.Handler(root).handlePost(request)
}

var root = {
    get: function (request)  // GET https://script.google.com/macros/s/<DeploymentID>/exec
    {
        return AppsScriptRouter.Helpers.returnJSON({ status: "ok" })
    },
    post: function (request) // POST https://script.google.com/macros/s/<DeploymentID>/exec
    {
        return AppsScriptRouter.Helpers.returnJSON({ status: "ok" })
    },
    path1:
    {
        get: function (request)  // GET https://script.google.com/macros/s/<DeploymentID>/exec/path1
        {
            return AppsScriptRouter.Helpers.returnJSON({ status: "ok" })
        },
        post: function (request) 
        {
            return AppsScriptRouter.Helpers.returnJSON({ status: "ok" })
        },
        innerpath1:
        {
            get: function (request)  // GET https://script.google.com/macros/s/<DeploymentID>/exec/path1/innerpath1
            {
                return AppsScriptRouter.Helpers.returnJSON({ status: "ok" })
            },
            post: function (request) // POST https://script.google.com/macros/s/<DeploymentID>/exec/path1/innerpath1
            {
                return AppsScriptRouter.Helpers.returnJSON({ status: "ok" })
            }
        }
    },
    path2:
    {
        innerpath1:
        {
            innerinnerpath1:
            {
                get: function (request) // GET https://script.google.com/macros/s/<DeploymentID>/exec/path2/innerpath1/innerinnerpath1
                {
                    return AppsScriptRouter.Helpers.returnJSON({ status: "ok" })
                }
            }
        }
    }
}
```

With TypeScript, you can make use of namespaces to break this into multiple files.

Apps Script itself is very limited to support a proper web application. Besides it can only process get and post methods, it also lacks custom return codes and the path traversing with `pathInfo` is actually undocumented and will require [access token](https://developers.google.com/apps-script/reference/script/script-app#getOAuthToken()) even if the access is set as anonymous (I have reported the unexpected behaviour but received no response: https://issuetracker.google.com/issues/133299026).

I have gave up working on this for now until Apps Script gets better, possibly till ES 6 support.

**Comment by coccoinomane** [comment]
Thank you so much Chen for your explanation.
I really like your approach, very modular and clean.
I understand your reasons for not working anymore on the project, and I have added a star on your issue to Google.

A quick question: If I wanted to output HTML and not only JSON, I would just need to add a function in Helpers.ts which wraps CreateHTMLOutput, correct?

Thanks,
Guido

**Comment by Cerlancism** [comment]
I think you can just directly return it like `return HtmlService.createHtmlOutput('<b>Hello, world!</b>')` within a get function in your router literal as you can build more things to it like method chaining.

**Comment by coccoinomane** [comment]
Thank you Chen! I will try that.
Have a nice day,
Guido
